### ISSUE TITLE
how to add a new slurmd c3?

### ISSUE THREAD

**Issue by yulingao** [giovtorres/slurm-docker-cluster#13]
i have tried a lot of times, but i still have a 2 nodes slurm cluster

**Comment by pablohe** [comment]
Hi, 
I did it, 

##  Added in composer.xml:

 ```
  c3:
    image: slurm-docker-cluster:19.05.1
    command: ["slurmd"]
    hostname: c3
    container_name: c3
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - slurm_jobdir:/data
      - var_log_slurm:/var/log/slurm
    expose:
      - "6818"
    depends_on:
      - "slurmctld"
```

## replace in slurm.conf

```
NodeName=c[1-2] RealMemory=1000 State=UNKNOWN 

```
by
```
NodeName=c[1-3] RealMemory=1000 State=UNKNOWN 

```
and 
```
PartitionName=normal Default=yes Nodes=c[1-2] Priority=50 DefMemPerCPU=500 Shared=NO MaxNodes=1 MaxTime=5-00:00:00 DefaultTime=5-00:00:00 State=UP
```
by
```
PartitionName=normal Default=yes Nodes=c[1-3] Priority=50 DefMemPerCPU=500 Shared=NO MaxNodes=1 MaxTime=5-00:00:00 DefaultTime=5-00:00:00 State=UP
```

## apply the changes 

docker-compose stop
docker build -t slurm-docker-cluster:19.05.1 .
