### ISSUE TITLE
swarm mode

### ISSUE THREAD

**Issue by thistleknot** [giovtorres/slurm-docker-cluster#14]
I found this guide
https://hub.docker.com/r/lvarin/slurm-docker-cluster

but it doesn't actually replicate the c1 workers

found this as well
https://stackoverflow.com/questions/49518376/docker-swarm-how-to-balance-already-running-containers-in-a-swarm-cluster

looks like I need to modify docker-compose to include something like
please advise
```
deploy:
      restart_policy:
        condition: any
      mode: replicated
      replicas: 5
      placement:
        constraints: [node.role == worker]
```
